name: api_testing_suite
description: API Testing Suite for APIDash
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.1
  uuid: ^3.0.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  apidash_core:
    path: ../apidash_core
  faker: ^2.0.0
  http: ^1.1.0
  dio: ^5.3.0
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.5
  freezed: ^2.5.7
  json_serializable: ^6.9.4
  test: ^1.24.0

flutter:
  uses-material-design: true
